#!/bin/bash
echo "🔍 Quick Deployment Check"
echo "========================"
echo ""
echo "✅ Required files:"
[ -f "api/index.js" ] && echo "  ✓ api/index.js" || echo "  ✗ api/index.js MISSING"
[ -f "vercel.json" ] && echo "  ✓ vercel.json" || echo "  ✗ vercel.json MISSING"
[ -f "src/app.js" ] && echo "  ✓ src/app.js" || echo "  ✗ src/app.js MISSING"
[ -f "package.json" ] && echo "  ✓ package.json" || echo "  ✗ package.json MISSING"
echo ""
echo "📝 Next steps in Vercel Dashboard:"
echo "1. Go to Functions tab - check if api/index.js is listed"
echo "2. Go to Deployments → Latest → Build Logs"
echo "3. Look for 'Building api/index.js' in logs"
echo "4. Test: https://your-app.vercel.app/health"
echo ""
echo "📖 See CHECK_DEPLOYMENT.md for detailed troubleshooting"
